[app]
name = "Lemmings"
category = "Badge"

[entry]
class = "Lemmings"

[metadata]
author = "pikesley"
license = "MIT"
url = "https://www.github.com/pikesley/tildagon-lemmings"
description = "Some lemmings ambling around your badge"
version = "0.0.9"
